apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiki
  template:
    metadata:
      labels:
        app: kiki
    spec:
      imagePullSecrets:
        - name: container-registry-secrets
      containers:
        - name: kiki
          image: docker.pkg.github.com/matootie/kiki/kiki:latest
          env:
            - name: KIKI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kiki-creds
                  key: bot-token
          resources:
            requests:
              memory: 128M
              cpu: 50m
            limits:
              memory: 256M
              cpu: 100m
