apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiki
  namespace: kiki
  labels:
    app: kiki
spec:
  selector:
    matchLabels:
      app: kiki
  template:
    metadata:
      labels:
        app: kiki
    spec:
      containers:
        - image: docker.pkg.github.com/matootie/kiki/kiki:v0.6.5-alpha
          name: kiki
          resources:
            requests:
              cpu: "50m"
              memory: "50M"
            limits:
              cpu: "100m"
              memory: "100M"
          env:
            - name: REDIS_URL
              value: "redis://redis"
            - name: KIKI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kiki-secrets
                  key: token
      imagePullSecrets:
        - name: gh-registry
