apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiki
  namespace: kiki
  labels:
    app: kiki
spec:
  selector:
    matchLabels:
      app: kiki
  template:
    metadata:
      labels:
        app: kiki
    spec:
      containers:
        - image: docker.pkg.github.com/matootie/kiki/kiki
          name: kiki
          resources:
            requests:
              cpu: "50m"
              memory: "50M"
            limits:
              cpu: "100m"
              memory: "100M"
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_USER
              value: kiki
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: kiki-secrets
                  key: postgres-pass
            - name: POSTGRES_NAME
              value: kiki
            - name: KIKI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kiki-secrets
                  key: token
      imagePullSecrets:
        - name: github-docker
