kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: kiki
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: kiki
  labels:
    app: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:6.0.3
          name: redis
          resources:
            requests:
              cpu: "20m"
              memory: "100M"
            limits:
              cpu: "50m"
              memory: "150M"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 1Gi
