name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Publish Image
        id: publish-image
        uses: matootie/github-docker@v1.0.1
        with:
          username: matootie
          personalAccessToken: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Save DigitalOcean Kubernetes Config
        uses: matootie/dokube@v1.2.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: cluster
          namespace: kiki

      - name: Update Deployment
        run: kubectl set image deployment.apps/kiki kiki=${{ steps.publish-image.outputs.imageURL }}
