name: Continuous Delivery

on:
  release:
    action:
      - created
      - prereleased

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build and push image
        uses: pangzineng/Github-Action-One-Click-Docker@master
        env:
          DOCKER_REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          DOCKER_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          DOCKER_IMAGE_TAG: ${GITHUB_REF:11}

      - name: Save DigitalOcean kubeconfig
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show k8s-cluster-name > $GITHUB_WORKSPACE/.kubeconfig

      - name: Set kubectl context
        uses: azure/k8s-actions/k8s-set-context@master
        with:
          context: ${{ secrets.CLUSTER_NAME }}

      - name: Create Registry secret
        uses: azure/k8s-actions/k8s-create-secret@master
        with:
          container-registry-url: ${{ secrets.REGISTRY_URL }}
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: container-registry-secrets

      - name: Deploy to Kubernetes
        uses: azure/k8s-actions/k8s-deploy@master
        with:
          manifests: |
            manifests/release-deployment.yaml
          images: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/kiki:${GITHUB_REF:11}
          imagepullsecrets: |
            container-registry-secrets
