name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set env
        run: echo ::set-env name=IMAGE_TAG::$(echo ${GITHUB_REF:10})

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: matootie/kiki/kiki
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: docker.pkg.github.com
          tag_names: true

      - name: Save DigitalOcean kubeconfig
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show do-tor1-cluster > $GITHUB_WORKSPACE/.kubeconfig

      - name: Set kubectl context
        uses: azure/k8s-actions/k8s-set-context@master
        with:
          context: ${{ secrets.CLUSTER_NAME }}

      - name: Create Registry secret
        uses: azure/k8s-actions/k8s-create-secret@master
        with:
          container-registry-url: ${{ secrets.REGISTRY_URL }}
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: container-registry-secrets

      - name: Deploy to Kubernetes
        uses: azure/k8s-actions/k8s-deploy@master
        with:
          manifests: |
            manifests/release-deployment.yaml
          images: |
            docker.pkg.github.com/matootie/kiki/kiki:${IMAGE_TAG}
          imagepullsecrets: |
            container-registry-secrets
