name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get version
        id: gv
        run: echo "::set-output name=version::${GITHUB_REF##*/}"

      - name: Publish Image
        id: publish-image
        uses: matootie/github-docker@v2.2.3
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          buildArg: |
            VERSION=${{ steps.gv.outputs.version }}

      - name: Save DigitalOcean Kubernetes Config
        uses: matootie/dokube@v1.3.1
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: yoiksoft
          namespace: kiki

      - name: Update Deployment
        run: kubectl set image deployment.apps/kiki kiki=${{ steps.publish-image.outputs.imageURL }}

      - name: Wait for Deployment
        run: kubectl rollout status deployment/kiki -w

      - name: Send out Webhook
        uses: ./.github/actions/kiki-release-notifier
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          webhookURL: ${{ secrets.WEBHOOK_URL }}
