name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: matootie/kiki/kiki
          username: matootie
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: docker.pkg.github.com
          tag_names: true

      - name: Save DigitalOcean kubeconfig
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show cluster > $GITHUB_WORKSPACE/.kubeconfig

      - name: Set kubectl context
        uses: azure/k8s-actions/k8s-set-context@master
        with:
          kubeconfig: '${cat $GITHUB_WORKSPACE/.kubeconfig}'
          context: 'do-tor1-cluster'

      - name: Create Registry secret
        uses: azure/k8s-actions/k8s-create-secret@master
        with:
          container-registry-url: docker.pkg.github.com
          container-registry-username: matootie
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: container-registry-secrets

      - name: Deploy to Kubernetes
        uses: azure/k8s-actions/k8s-deploy@master
        with:
          manifests: |
            manifests/release-deployment.yaml
          images: |
            docker.pkg.github.com/matootie/kiki/kiki:${GITHUB_REF:10}
          imagepullsecrets: |
            container-registry-secrets
