name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Build and Publish Package to GitHub Package Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: matootie/kiki/kiki
          username: matootie
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: docker.pkg.github.com
          tag_names: true

      - name: Save DigitalOcean Kubernetes Config
        uses: uniappca/dokube@v1.0.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: cluster

      - name: Update Deployment
        run: kubectl set image deployment.apps/kiki kiki=docker.pkg.github.com/matootie/kiki/kiki:${GITHUB_REF:10}
