name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Build and Publish Package to GitHub Package Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: matootie/kiki/kiki
          username: matootie
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: docker.pkg.github.com
          tag_names: true

      - name: Save DigitalOcean Kubernetes Config
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show cluster > /github/workspace/.kubeconfig

      - name: Deploy to Kubernetes
        uses: docker://lachlanevenson/k8s-kubectl
        with:
          args: --kubeconfig=/github/workspace/.kubeconfig set image deployment.apps/kiki kiki=kiki:${GITHUB_REF:10}

      - name: Verify Deployment
        uses: docker://lachlanevenson/k8s-kubectl
        with:
          args: --kubeconfig=/github/workspace/.kubeconfig rollout status deployment.apps/kiki
