name: Continuous Integration

on:
  push:
    branches:
      - master
  release:
    action:
      - created
      - prereleased

jobs:
  lint:
    name: Lint Kiki
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools
          pip install pipenv
          pipenv install --dev

      - name: Lint with pylint
        run: |
          pipenv run pylint kiki

      - name: Build and push image (latest)
        uses: pangzineng/Github-Action-One-Click-Docker@master
        env:
          DOCKER_REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          DOCKER_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          DOCKER_IMAGE_TAG: latest

      - name: Build and push image (commit sha)
        uses: pangzineng/Github-Action-One-Click-Docker@master
        env:
          DOCKER_REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          DOCKER_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          DOCKER_IMAGE_TAG: ${{ github.sha }}
        if: github.event_name == 'push'

      - name: Build and push image (release ref)
        uses: pangzineng/Github-Action-One-Click-Docker@master
        env:
          DOCKER_REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          DOCKER_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          DOCKER_IMAGE_TAG: ${{ github.ref }}
        if: github.event_name == 'release'

      - name: Set kubectl context
        uses: azure/k8s-actions/k8s-set-context@master
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: 'do-tor1-clusta'

      - name: Create Registry secret
        uses: azure/k8s-actions/k8s-create-secret@master
        with:
          container-registry-url: ${{ secrets.REGISTRY_URL }}
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: container-registry-secrets

      - name: Deploy to Kubernetes (latest)
        uses: azure/k8s-actions/k8s-deploy@master
        with:
          manifests: |
            manifests/latest-deployment.yaml
          images: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/kiki:${{ github.sha }}
          imagepullsecrets: |
            container-registry-secrets
        if: github.event_name == 'push'

      - name: Deploy to Kubernetes (release)
        uses: azure/k8s-actions/k8s-deploy@master
        with:
          manifests: |
            manifests/release-deployment.yaml
          images: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/kiki:${{ github.ref }}
          imagepullsecrets: |
            container-registry-secrets
        if: github.event_name == 'release'
