name: Lint check

on: [push]

jobs:
  lint:
    name: Lint Kiki
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Lint with pylint
      run: |
        pipenv run pylint kiki
