name: Continuous Integration

on:
  push:
    branches:
      - master
  release:
    action:
      - created
      - prereleased

jobs:
  lint:
    name: Lint Kiki
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools
          pip install pipenv
          pipenv install --dev

      - name: Lint with pylint
        run: |
          pipenv run pylint kiki

      - name: Log into Docker
        uses: actions/docker/login@master
        env:
          DOCKER_REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          DOCKER_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Publish Docker image (latest)
        uses: actions/docker/cli-multi@master
        with:
          args: docker build -t ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/kiki:latest
      # - name: Publish Docker image (latest)
      #   uses: elgohr/Publish-Docker-Github-Action@master
      #   with:
      #     name: kiki:latest
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}
      # - name: Publish Docker image (commit ref)
      #   uses: elgohr/Publish-Docker-Github-Action@master
      #   with:
      #     name: kiki:${{ github.sha }}
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}
      #     registry: ${{ secrets.REGISTRY_URL }}
      #   if: github.event_name == 'push'
      # - name: Publish Docker image (release)
      #   uses: elgohr/Publish-Docker-Github-Action@master
      #   with:
      #     name: kiki:${{ github.ref }}
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}
      #     registry: ${{ secrets.REGISTRY_URL }}
      #   if: github.event_name == 'release'
      # - name: Set kubectl context
      #   uses: azure/k8s-actions/k8s-set-context@master
      #   with:
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}
      #     context: "cluster"
      # - name: Create Registry secret
      #   uses: azure/k8s-actions/k8s-create-secret@master
      #   with:
      #     container-registry-url: ${{ secrets.REGISTRY_URL }}
      #     container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
      #     container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      #     secret-name: container-registry-secrets
      # - name: Deploy to Kubernetes
      #   uses: azure/k8s-actions/k8s-deploy@master
      #   with:
      #     manifests: |
      #       manifests/deployment.yaml
      #     images: |
      #       ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/kiki:${{ github.sha }}
      #     imagepullsecrets: |
      #       container-registry-secrets
